language: python
python:
- '3.6'
# command to install dependencies
# install:
#  - pip install -r requirements.txt
# command to run tests
script:
  - cd s3_uploader
  - echo "skipping tests"
deploy:
  provider: lambda
  function_name: fw-science-data-collection-s3-uploader-us-east-2
  region: us-east-2
  role: arn:aws:iam::147907368845:role/service-role/fw-science-us-east-2
  runtime: python3.6
  module_name: fw-science-data-collection-s3-uploader-us-east-2
  handler_name: lambda_handler
  on:
    branch: feature/s3-uploader-dev
  access_key_id:
    secure: cipa8eVjrdmJFgbDFf/qZciTGWTwZ3AHwY6WyvyWWlWlUIB70GTk/Ad530RzdYqt4kVIMfLIqlq5hD3Ho0/Ub3Eta03mcyDqgCPwQ1mWwBUizmeHK2Rx0CfWtkXfDJZLhAiYcsXX3dJyHM/XiKvzhqurceYsjsD4L5ezf6y95O96oXP8oIPhYx3C1FvRgSTrUNvkJa7pgKj7XxtQ2KDA3D1Svc2NMliZlYAFf8T3Y8x+2OV1XN/XBK5GrTBkI8mxIckrRpa9s4LJCkzkhWLZBVM/VPwHf77zYZFeNvIAZ/0QtjY9oWNWGPFu1zFSw2GkoYyO5nLgvXSgPAu+kIoQH9bMlsR84Dt3D7McH1gFAbDqamaRr38/o3fhYohm8Ms7+5rAo3Nr0KHgO4KUg54aHU6uiS54r0BLgOkOWd6v+c1oHzEjFLr0EU5H4WAAxKRs20guDxIhcSUR3dN6MY2CRCfie3Y6tVoaWN+bP89+rfPzP9NPUBRXmN+RnaA/mjVVM/KGaemz5CfaMuCFwkEofw3By5Em+Rfmsb5mEOItxf6ZH/ft/mn5RS0z0/iYDYZbC0tizj/Zba3xeph0Ru+oTlSQ5VBtT/GBhKv0Z4yuxrbbofLZy4ZINhBwDm30MKJjc9f4aOsqIgmKs55/ubB+BpRDiBlwkN/KKhSFx/6QFM0=
  secret_access_key:
    secure: EqXxdPo6PL/sUQ+hzfFmyQxMcEoso+41/t7K3xiJ9uj+1+2mo5I+mdNm3X6+39P9G1IOgdAyR/8f4p6rfm+IPi7m+OWHeJauIF/JdYr8Blmafvq3jx6ZA6Cprt8a5ALmYO0YMWi+MBM8AQN2U/PpRmMHHlcgXI8omMMpMLdeJ0fjAjvCDpZqoTXFDOlyW1Hn3PH9eaolhoaEqQcjbeYZrFnMUb1pG/0uOMxAn6VlxrPW7adnPH2jlKHVPYo3GSyDrtwwf4nUKfMvBTeiMRn1mo9pgWslHoYjVYIVAgYYXSpI+TXpWWsNqQnurM3GzayeoMvQZZgds5vNg2bnTypUww4B0FVCs7BnrGnl8pYFF088Gh78gwn9gH7ijinIeypMNK/TXoRk5Ze2b7XuMD0pUJBlu9JuCoXho6gAwrF5C44TWHBRNdE6wYFGcbSXLGL9dzLH0SAGWUt4aaCq1cOe+AiPFpFocm/+Pt4cqBWf/EJFA+jQVMqqxG7OaTutkW2pKdB6HSOOaYwPhI2JN3CwPUS4v4O+Q54baAsZwee6wd+K20rVgmUWQXVwYGAQv5GAHFaq+IMqf0FfeDWICG76ySkbNqnB/id7+5tS0OocUib/R6ebMut289yVNDfDSLaNkYKKNdZdBfRtVobwHMXvQ4T2hppnjX1/MS61uTPZ5dY=
